services:
  cds-backend-service:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: imagename-backend:latest
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw  # Only make cache writable
    ports:
      - "8000:8000"
    restart: always
    container_name: cds-backend-container
    env_file:
      - .env
  cds-frontend-service:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=http://cds-backend-service:8000
    image: cds-frontend:latest
    ports:
      - "8080:8080"
    restart: always
    container_name: cds-frontend-container

networks:
  healthcare_cds: