FROM node:22-alpine
WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .

RUN npm run build
EXPOSE 8080
CMD ["npm", "start"]